In [1]:
import torch


In [24]:
ov = torch.randn([2,2], dtype=float)
print(ov)

tensor([[-1.6942,  1.3901],
        [ 1.3345,  1.2460]], dtype=torch.float64)


In [34]:
vec_ov = torch.reshape(ov, (ov.numel(), 1))
print(vec_ov)

diagonal_mat = torch.eye(vec_ov.shape[0])
print(diagonal_mat)

res_mat = vec_ov * diagonal_mat
print(res_mat)

tensor([[-1.6942],
        [ 1.3901],
        [ 1.3345],
        [ 1.2460]], dtype=torch.float64)
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [36]:
torch.eye(2,3).T

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In [31]:
mat1 = torch.tensor([[1,1],[2,2]])
mat2 = torch.tensor([[1,2],[3,4]])

print(mat1, "\n", mat2)

print(f"mat1 * mat2 = {mat1*mat2}")
print(f"torch.matmul = {torch.matmul(mat1, mat2)}")

tensor([[1, 1],
        [2, 2]]) 
 tensor([[1, 2],
        [3, 4]])
mat1 * mat2 = tensor([[1, 2],
        [6, 8]])
torch.matmul = tensor([[ 4,  6],
        [ 8, 12]])
